In [3]:
import cv2
import numpy as np

# Create a sample image (or load one)

#image = np.array([[10, 20, 30],
#            [40, 50, 60],
#                  [70, 80, 90]])

image = cv2.imread('Animal_04.jpg')

# Calculate mean and standard deviation
(mean, stddev) = cv2.meanStdDev(image, cv2.COLOR_BGR2HSV)
colorStats = np.concatenate([mean, stddev]).flatten()

print(f"Image: {image}")
#print(f"Mean: {mean}")
#print(f"Standard Deviation: {stddev}")
print(f"ColorStats: {colorStats}")

Image: [[[ 47 117 111]
  [ 50 120 114]
  [ 54 121 118]
  ...
  [ 34 104 111]
  [ 35 105 112]
  [ 37 108 112]]

 [[ 49 119 113]
  [ 51 121 115]
  [ 53 120 117]
  ...
  [ 36 106 113]
  [ 37 107 114]
  [ 39 110 114]]

 [[ 53 123 117]
  [ 53 123 117]
  [ 52 119 116]
  ...
  [ 39 111 118]
  [ 40 113 117]
  [ 41 114 118]]

 ...

 [[176 210 234]
  [176 210 234]
  [182 216 240]
  ...
  [  0  86  78]
  [ 26 130 119]
  [ 19 148 133]]

 [[180 214 238]
  [175 209 233]
  [178 212 236]
  ...
  [  0  83  74]
  [ 23 129 116]
  [ 26 158 141]]

 [[180 214 238]
  [176 210 234]
  [178 212 236]
  ...
  [  3  92  83]
  [ 22 130 117]
  [ 28 162 144]]]
ColorStats: [ 96.16996791 142.36579045 155.60110453  53.26109683  51.27674416
  59.34032116]
